export const NETWORK_ERROR_CODES = {
  ECONNABORTED: 'ECONNABORTED',
  ETIMEDOUT: 'ETIMEDOUT',
  ECONNREFUSED: 'ECONNREFUSED',
  ENOTFOUND: 'ENOTFOUND',
} as const;

export const REDIS_ERROR_CODES = {
  READONLY: 'READONLY',
} as const;

export const HTTP_STATUS_RANGES = {
  CLIENT_ERROR_START: 400,
  CLIENT_ERROR_END: 500,
  SERVER_ERROR_START: 500,
  SERVER_ERROR_END: 600,
} as const;

export const ERROR_MESSAGES = {
  REQUEST_TIMEOUT: 'Request timeout',
  REQUEST_FAILED: 'Request failed',
  UNKNOWN_ERROR: 'Unknown error',
} as const;
